repos:
  - repo: local
    hooks:
      - id: black-format
        name: "Black – code formatter"
        entry: poetry run black
        language: system
        types: [python]
        args: ["--line-length", "88"]
        pass_filenames: true
      - id: ruff-lint
        name: "Ruff – linter (auto-fix)"
        entry: poetry run ruff check
        language: system
        types: [python]
        args: ["--fix"]
        pass_filenames: true
      - id: mypy-type-check
        name: "Mypy – static type checker"
        entry: poetry run mypy
        language: system
        types: [python]
        args: ["src"]
        pass_filenames: false 