name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: "${{ runner.os }}-poetry-${{ hashFiles('pyproject.toml') }}"
      - name: Install poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install --no-interaction
      - name: Lint
        run: poetry run ruff check .
      - name: Format
        run: poetry run black --check .
      - name: Type check
        run: poetry run mypy src
      - name: Tests
        run: poetry run pytest
